# Generated by Django 4.2 on 2024-03-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('ename', models.CharField(max_length=30)),
                ('eid', models.IntegerField()),
                ('eemail', models.EmailField(max_length=254)),
                ('ephn', models.BigIntegerField()),
                ('esal', models.FloatField()),
            ],
        ),
    ]
